apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pyechoserver
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: pyechoserver
    spec:
      containers:
      - name: pyechoserver
        image: dseeley/pyechoserver:1.0.0
        ports:
        - containerPort: 8080
